from __future__ import annotations

VIENEU = "vieneu"
EDGE = "edge-tts"

LANGUAGES = [
    {"code": "vi", "label": "Vietnamese", "flag": "🇻🇳", "engine": VIENEU},
    {"code": "en", "label": "English", "flag": "🇬🇧", "engine": EDGE},
    {"code": "zh", "label": "Chinese", "flag": "🇨🇳", "engine": EDGE},
    {"code": "ja", "label": "Japanese", "flag": "🇯🇵", "engine": EDGE},
    {"code": "ko", "label": "Korean", "flag": "🇰🇷", "engine": EDGE},
    {"code": "fr", "label": "French", "flag": "🇫🇷", "engine": EDGE},
    {"code": "de", "label": "German", "flag": "🇩🇪", "engine": EDGE},
    {"code": "es", "label": "Spanish", "flag": "🇪🇸", "engine": EDGE},
]

VOICES = [
    {
        "id": "Minh Đức",
        "name": "Minh Đức",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Phạm Tuyên",
        "name": "Phạm Tuyên",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Thái Sơn",
        "name": "Thái Sơn",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Xuân Vĩnh",
        "name": "Xuân Vĩnh",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Thanh Bình",
        "name": "Thanh Bình",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Minh Triết",
        "name": "Minh Triết",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Quang Sơn",
        "name": "Quang Sơn",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Đức Trí",
        "name": "Đức Trí",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Adam",
        "name": "Adam",
        "gender": "male",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Trúc Ly",
        "name": "Trúc Ly",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Ngọc Linh",
        "name": "Ngọc Linh",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Đoan Trang",
        "name": "Đoan Trang",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Mai Anh",
        "name": "Mai Anh",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Thục Đoan",
        "name": "Thục Đoan",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Thùy Dung",
        "name": "Thùy Dung",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Ngọc Trân",
        "name": "Ngọc Trân",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Mỹ Duyên",
        "name": "Mỹ Duyên",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Quỳnh Anh",
        "name": "Quỳnh Anh",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Kim Thanh",
        "name": "Kim Thanh",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "Ngọc Huyền",
        "name": "Ngọc Huyền",
        "gender": "female",
        "locale": "vi-VN",
        "language": "vi",
        "engine": VIENEU,
    },
    {
        "id": "en-US-JennyNeural",
        "name": "Jenny",
        "gender": "female",
        "locale": "en-US",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-US-AriaNeural",
        "name": "Aria",
        "gender": "female",
        "locale": "en-US",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-US-MichelleNeural",
        "name": "Michelle",
        "gender": "female",
        "locale": "en-US",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-GB-SoniaNeural",
        "name": "Sonia",
        "gender": "female",
        "locale": "en-GB",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-AU-NatashaNeural",
        "name": "Natasha",
        "gender": "female",
        "locale": "en-AU",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-US-GuyNeural",
        "name": "Guy",
        "gender": "male",
        "locale": "en-US",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-US-EricNeural",
        "name": "Eric",
        "gender": "male",
        "locale": "en-US",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-GB-RyanNeural",
        "name": "Ryan",
        "gender": "male",
        "locale": "en-GB",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "en-AU-WilliamMultilingualNeural",
        "name": "William",
        "gender": "male",
        "locale": "en-AU",
        "language": "en",
        "engine": EDGE,
    },
    {
        "id": "zh-CN-XiaoxiaoNeural",
        "name": "Xiaoxiao",
        "gender": "female",
        "locale": "zh-CN",
        "language": "zh",
        "engine": EDGE,
    },
    {
        "id": "zh-CN-XiaoyiNeural",
        "name": "Xiaoyi",
        "gender": "female",
        "locale": "zh-CN",
        "language": "zh",
        "engine": EDGE,
    },
    {
        "id": "zh-CN-YunxiNeural",
        "name": "Yunxi",
        "gender": "male",
        "locale": "zh-CN",
        "language": "zh",
        "engine": EDGE,
    },
    {
        "id": "zh-CN-YunjianNeural",
        "name": "Yunjian",
        "gender": "male",
        "locale": "zh-CN",
        "language": "zh",
        "engine": EDGE,
    },
    {
        "id": "zh-CN-YunyangNeural",
        "name": "Yunyang",
        "gender": "male",
        "locale": "zh-CN",
        "language": "zh",
        "engine": EDGE,
    },
    {
        "id": "ja-JP-NanamiNeural",
        "name": "Nanami",
        "gender": "female",
        "locale": "ja-JP",
        "language": "ja",
        "engine": EDGE,
    },
    {
        "id": "ja-JP-KeitaNeural",
        "name": "Keita",
        "gender": "male",
        "locale": "ja-JP",
        "language": "ja",
        "engine": EDGE,
    },
    {
        "id": "ko-KR-SunHiNeural",
        "name": "SunHi",
        "gender": "female",
        "locale": "ko-KR",
        "language": "ko",
        "engine": EDGE,
    },
    {
        "id": "ko-KR-InJoonNeural",
        "name": "InJoon",
        "gender": "male",
        "locale": "ko-KR",
        "language": "ko",
        "engine": EDGE,
    },
    {
        "id": "fr-FR-DeniseNeural",
        "name": "Denise",
        "gender": "female",
        "locale": "fr-FR",
        "language": "fr",
        "engine": EDGE,
    },
    {
        "id": "fr-FR-EloiseNeural",
        "name": "Eloise",
        "gender": "female",
        "locale": "fr-FR",
        "language": "fr",
        "engine": EDGE,
    },
    {
        "id": "fr-FR-HenriNeural",
        "name": "Henri",
        "gender": "male",
        "locale": "fr-FR",
        "language": "fr",
        "engine": EDGE,
    },
    {
        "id": "de-DE-KatjaNeural",
        "name": "Katja",
        "gender": "female",
        "locale": "de-DE",
        "language": "de",
        "engine": EDGE,
    },
    {
        "id": "de-DE-AmalaNeural",
        "name": "Amala",
        "gender": "female",
        "locale": "de-DE",
        "language": "de",
        "engine": EDGE,
    },
    {
        "id": "de-DE-ConradNeural",
        "name": "Conrad",
        "gender": "male",
        "locale": "de-DE",
        "language": "de",
        "engine": EDGE,
    },
    {
        "id": "de-DE-KillianNeural",
        "name": "Killian",
        "gender": "male",
        "locale": "de-DE",
        "language": "de",
        "engine": EDGE,
    },
    {
        "id": "es-ES-ElviraNeural",
        "name": "Elvira",
        "gender": "female",
        "locale": "es-ES",
        "language": "es",
        "engine": EDGE,
    },
    {
        "id": "es-ES-XimenaNeural",
        "name": "Ximena",
        "gender": "female",
        "locale": "es-ES",
        "language": "es",
        "engine": EDGE,
    },
    {
        "id": "es-ES-AlvaroNeural",
        "name": "Alvaro",
        "gender": "male",
        "locale": "es-ES",
        "language": "es",
        "engine": EDGE,
    },
]

GREETINGS = {
    "vi": "Xin chào, chào mừng bạn đến với AI Trans Clips, chúc bạn có một ngày vui vẻ?",
    "en": "Hello, welcome to AI Trans Clips. Have a wonderful day!",
    "zh": "你好，欢迎来到 AI Trans Clips，祝你今天愉快！",
    "ja": "こんにちは、AI Trans Clips へようこそ。良い一日をお過ごしください！",
    "ko": "안녕하세요, AI Trans Clips에 오신 것을 환영합니다. 좋은 하루 보내세요!",
    "fr": "Bonjour, bienvenue sur AI Trans Clips. Passez une excellente journée !",
    "de": "Hallo, willkommen bei AI Trans Clips. Haben Sie einen schönen Tag!",
    "es": "Hola, bienvenido a AI Trans Clips. ¡Que tengas un buen día!",
}


def greeting_for(language: str) -> str:
    return GREETINGS.get(language, GREETINGS["en"])


def voices_for_language(language: str) -> list[dict]:
    return [voice for voice in VOICES if voice["language"] == language]


def catalog() -> dict:
    return {"languages": LANGUAGES, "voices": VOICES}
